version: '3'
services:
  microservice1:
    build: ../microservice
    ports:
      - "8081:8080"   # Exposing the service on port 8081
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
